import { Payments } from "razorpay/dist/types/payments";

export type AccountType = {
  /**
   * Type of the Account, either `admin` or `user`.
   */
  accountType: "admin" | "user";
};

export type AdminType = AccountType & {
  /**
   * ID of the Admin.
   */
  adminId: string;

  /**
   * Email Address of the Admin.
   */
  email: string;

  /**
   * Name of the Admin.
   */
  name: string;
};

export type UserType = AccountType & {
  /**
   * Customer Registration ID.
   */
  userId: string;

  /**
   * Phone/Mobile Number of the Customer/User.
   */
  phoneNumber: string;

  /**
   * Email Address of the Customer/User.
   */
  email: string;

  /**
   * Name of the Customer/User.
   */
  name: string;

  /**
   * Customer Details ID from the customerDetails Table.
   */
  customerDetailsId: string;
};

export type GetPriceBreakDetailsType = {
  /**
   * Price Before Calculating the GST (Base Price).
   */
  priceBeforeGST: number;

  /**
   * Total GST Amount to be Paid by the User.
   */
  gstAmount: number;

  /**
   * Price after adding the GST to the Base Price (basePrice + GST).
   */
  priceWithGST: number;

  /**
   * Discount Amount based on the Coupon Value.
   */
  discountPrice: number;

  /**
   * Price after deducting the Discount Amount (basePrice - discountPrice) after adding the GST to the Base Price (basePrice + GST) .
   */
  priceWithDiscountWithGST: number;

  /**
   * Payment Gateway Charges in Rupees based on total Payable Amount by calculating with the Percentage charged by Payment Gateways.
   */
  paymentGatewayValue: number;

  /**
   * The Total Payable Amount for the Customer.
   */
  totalPayable: number;

  /**
   * Total Price of the Item.
   */
  totalItemPrice: number;

  /**
   * The Revenue Generated by the Store for each Order after deducting the Payment Gateway Amount (paymentGatewayValue) and calculation will be like (totalPayable - paymentGatewayValue).
   */
  storeRevenue: number;
};

export interface RazorPayPaymentType extends Payments.RazorpayPayment {}
